url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jingzong Li" # the name of your site, e.g. ACME Corp.
description: "Art of Life / 心有山海，靜而不爭"
