menu:
# - {name: 'people', url: '/people.html'}
- {name: 'publications', url: '/publications.html'}
- {name: 'cv', url: '/cv.html'}
- {name: 'gallery', url: '/gallery.html'}
- {name: 'contact', url: '/contact.html'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/kanonjz'}
- {icon: 'readme', link: 'https://kanonjz.github.io/'}
- {icon: 'instagram', link: 'https://www.instagram.com/kanonnnnnnnnnnnn/'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jingzong-li-955a11120'}

contacts:
- {name: 'Jingzong Li', title: '', department: 'Department of Computer Science', institution: 'The Hang Seng University of Hong Kong', institution_address: 'Hang Shin Link, Siu Lek Yuen', district: 'Shatin, N.T.', city: 'Hong Kong', phone: '(000) 000-0000', email: 'jingzongli [a] hsu.edu.hk', office: 'M404', image: 'assets/img/home.jpg'}
