- title: 'Invited Reviewer'
  venue: 'IEEE Transactions on Network Science and Engineering (TNSE), IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)'

- title: 'Technical Program Committee'
  venue: 'HP3C''23'

- title: 'Artifact Evaluation Committee'
  venue: 'ACM SIGCOMM''24, ACM EuroSys''24, ACM SOSP''23, USENIX OSDI''23, USENIX ATC''23, MLSys''23, ACM CoNEXT''22'