- title: 'Invited Reviewer'
  venue: 'Conference on Computer Vision and Pattern Recognition (CVPR)</br>
  International Conference on Computer Vision (ICCV)</br>
  European Conference on Computer Vision (ECCV)</br>
  IEEE Transactions on Network Science and Engineering (TNSE)</br> 
  IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)'

- title: 'Organizing Committee'
  venue: 'FAISys''25'

# - title: 'Technical Program Committee'
#   venue: 'HP3C''23'

- title: 'Artifact Evaluation Committee'
  venue: 'ACM EuroSys''26, ACM CoNEXT''25, ACM SIGCOMM''24, ACM EuroSys''24, ACM SOSP''23, USENIX OSDI''23, USENIX ATC''23, MLSys''23, ACM CoNEXT''22'